---
title: "R Notebook"
output: html_notebook
---


Clear environment of variables and packages  
=========================================

```{r}
# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 
# Clear environmet of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), detach, character.only = TRUE, unload = TRUE)
```

Load packages that include different functions  
=========================================

```{r}
# adding library
library(tidyverse)
library(GGally)
library(gridExtra)
library("readxl")
library(janitor)
library(stringr)
library(aod)
library(ggplot2)
library(stringi)
```

Load data and begin new EDA  
=========================================

```{r}
#loading data
demand <- read_csv('demand.csv')
# annual_demand <- read_csv('annual_demand.csv')
# fcst_error <- read_csv('fcst_error.csv')
# future_fcst <- read_csv('future_fcst.csv')
# lead_time <- read_csv('lead_time.csv')
# item_location_count <- read_csv('item_location_count.csv')
ots <- read_csv("ots.csv")
part_info <- read_csv("part_information.csv")
protected_inventory <- read_csv("protected_inventory.csv")
```




```{r}
# Demand data & annual demand data
# change column name to vndr_id
colnames(demand)[colnames(demand)=="whse_vndr_id"] <- "vndr_id"
# cost of each rhit
demand <- demand %>% mutate(cost_rhit = 15 * rhit, 
                            year = format(order_month,"%Y"),
                            item_id = substr(dim, 1, stri_length(dim)-3))


# summary(demand)
```

```{r}
# part information data 
# part_info <- part_info %>% mutate_if(is.character, as.factor)

part_info <- part_info %>%  mutate(cost_inventory = round(5.5* ((length*width*height)/1728), 3)) 
part_info <- subset(part_info, select= -c(length, width, height))


# part_info <- part_info %>% mutate(item_id = substr(part_info$dim, 1, stri_length(part_info$dim)-3))

# summary(part_info)
```

```{r}
# On Time Shipping data
date <- as.Date.character(ots$ots_month, '%M/%D/%Y')
ots <- ots %>%  mutate(ots = (early + on_time + pd_shipped) / (past_due + total_all),
                       year = format(date,'%Y'))

# summary(ots)

```


```{r}
# join demand and part_info table 
new <- left_join(demand, part_info, by = c("dim", "vndr_id")) %>% filter(fcst_daily >0)

indicators <- c("mx_ind","ngp_ind","lfna_ind","lfna_4c_ind")
new[indicators] <- lapply(new[indicators], factor)
new$part_cost[is.na(new$part_cost)] <- 0

summary(new)

```

```{r}
overstocked <- new %>% 
  mutate(order_point= fcst_daily*lead_time + safety_stock_days,
         stocking_ratio = days_on_hand/ lead_time,
         factor= if_else(new$item_id %in% protected_inventory$item_id, 1,0)) %>% 
  filter(stock_class!= "N", stocking_ratio>=2, factor == 0)%>% select(-factor) 

overstocked_ind <- overstocked[which(overstocked$mx_ind == 1 |overstocked$ngp_ind == 1 |overstocked$lfna_ind == 1 |overstocked$lfna_4c_ind == 1),]

table_a_vel <- overstocked %>% group_by(item_id, velocity, year) %>% 
  summarise(total_rhit = sum(rhit),
            total_rline = sum(rline),
            total_rhit_qtf = sum(rhit_qty),
            avg_rfill = 1-sum(rhit)/sum(rline),
            total_rcost = sum(cost_rhit),
            total_inventory_holding_cost = sum(cost_inventory),
            total_part_cost = sum(part_cost),
            avg_lead_time = mean(lead_time),
            avg_order_point = mean(order_point),
            avg_stocking_ratio = mean(stocking_ratio))
table_a_mar <- overstocked %>% group_by(item_id, marketing_category, year) %>% 
  summarise(total_rhit = sum(rhit),
            total_rline = sum(rline),
            total_rhit_qtf = sum(rhit_qty),
            avg_rfill = 1-sum(rhit)/sum(rline),
            total_rcost = sum(cost_rhit),
            total_inventory_holding_cost = sum(cost_inventory),
            total_part_cost = sum(part_cost),
            avg_lead_time = mean(lead_time),
            avg_order_point = mean(order_point),
            avg_stocking_ratio = mean(stocking_ratio))


table_a_ind_vel <- overstocked_ind %>% group_by(item_id, velocity, year) %>% 
  summarise(total_rhit = sum(rhit),
            total_rline = sum(rline),
            total_rhit_qtf = sum(rhit_qty),
            avg_rfill = 1-sum(rhit)/sum(rline),
            total_rcost = sum(cost_rhit),
            total_inventory_holding_cost = sum(cost_inventory),
            total_part_cost = sum(part_cost),
            avg_lead_time = mean(lead_time),
            avg_order_point = mean(order_point),
            avg_stocking_ratio = mean(stocking_ratio))

table_a_ind_mar <- overstocked_ind %>% group_by(item_id, marketing_category, year) %>% 
  summarise(total_rhit = sum(rhit),
            total_rline = sum(rline),
            total_rhit_qtf = sum(rhit_qty),
            avg_rfill = 1-sum(rhit)/sum(rline),
            total_rcost = sum(cost_rhit),
            total_inventory_holding_cost = sum(cost_inventory),
            total_part_cost = sum(part_cost),
            avg_lead_time = mean(lead_time),
            avg_order_point = mean(order_point),
            avg_stocking_ratio = mean(stocking_ratio))

overstocked
table_a_vel
# table_a
# sum(table_a$total_part_cost)
```


```{r}
avg_stocking <- new %>% 
  mutate(order_point= fcst_daily*lead_time + safety_stock_days,
         stocking_ratio = days_on_hand/ lead_time,
         factor= if_else(new$item_id %in% protected_inventory$item_id, 1,0)) %>% 
  filter(stock_class!= "N", stocking_ratio>1 & stocking_ratio< 2, factor == 0)%>% select(-factor) 


table_b_velocity <- avg_stocking %>% group_by(velocity, year) %>% 
  summarise(total_rhit = sum(rhit),
            total_rline = sum(rline),
            total_rhit_qtf = sum(rhit_qty),
            avg_rfill = 1-sum(rhit)/sum(rline),
            total_rcost = sum(cost_rhit),
            total_inventory_holding_cost = sum(cost_inventory),
            total_part_cost = sum(part_cost),
            avg_lead_time = mean(lead_time),
            avg_order_point = mean(order_point),
            avg_stocking_ratio = mean(stocking_ratio)) 

table_b_marketing <- avg_stocking %>% group_by(marketing_category, year) %>% 
  summarise(total_rhit = sum(rhit),
            total_rline = sum(rline),
            total_rhit_qtf = sum(rhit_qty),
            avg_rfill = 1-sum(rhit)/sum(rline),
            total_rcost = sum(cost_rhit),
            total_inventory_holding_cost = sum(cost_inventory),
            total_part_cost = sum(part_cost),
            avg_lead_time = mean(lead_time),
            avg_order_point = mean(order_point),
            avg_stocking_ratio = mean(stocking_ratio)) 

table_b_velocity

```




```{r}
# reducing avg stocking ratio by item id by
sub_table_a_vel <- table_a_vel %>% select(c(item_id, velocity, avg_stocking_ratio, year))
sub_table_a_mar <- table_a_mar %>% select(c(item_id, marketing_category, avg_stocking_ratio, year))
sub_table_a_ind_vel <- table_a_ind_vel %>% select(c(item_id, velocity, avg_stocking_ratio, year))
sub_table_a_ind_mar <- table_a_ind_mar %>% select(c(item_id, marketing_category, avg_stocking_ratio, year))
sub_table_b_velocity <- table_b_velocity %>% select(c(velocity, avg_stocking_ratio, year))
sub_table_b_marketing <- table_b_marketing %>% select(c(marketing_category, avg_stocking_ratio, year))

# difference is average desired reducing stocking ratio 
comparson_vel <- left_join(sub_table_a_vel,sub_table_b_velocity, by = c('year',"velocity")) %>% mutate(difference = avg_stocking_ratio.x - avg_stocking_ratio.y)
comparson_mar <- left_join(sub_table_a_mar,sub_table_b_marketing, by = c('year',"marketing_category")) %>% mutate(difference = avg_stocking_ratio.x - avg_stocking_ratio.y)
comparson_ind_vel <- left_join(sub_table_a_ind_vel,sub_table_b_velocity, by = c('year',"velocity")) %>% mutate(difference = avg_stocking_ratio.x - avg_stocking_ratio.y)
comparson_ind_mar <- left_join(sub_table_a_ind_mar,sub_table_b_marketing, by = c('year',"marketing_category")) %>% mutate(difference = avg_stocking_ratio.x - avg_stocking_ratio.y)
# On hand qty = stocking ratio* lead time * daily fcst 

df_vel <- left_join(comparson_vel, new, by = c("item_id", 'velocity', 'year'))
df_mar <- left_join(comparson_mar, new, by = c("item_id", 'marketing_category', 'year'))
df_ind_vel <- left_join(comparson_ind_vel, new, by = c("item_id", 'velocity', 'year'))
df_ind_mar <- left_join(comparson_ind_mar, new, by = c("item_id", 'marketing_category', 'year'))

final_vel <- df_vel %>% group_by(item_id,velocity,year) %>% 
  summarise(reduce_on_hand = round(mean(difference)*mean(lead_time)*mean(fcst_daily), 0),
            saving_part_cost = sum(part_cost)*reduce_on_hand,
            saving_holding_costing = sum(cost_inventory)*reduce_on_hand)

final_mar <- df_mar %>% group_by(item_id,marketing_category, year) %>% 
  summarise(reduce_on_hand = round(mean(difference)*mean(lead_time)*mean(fcst_daily), 0),
            saving_part_cost = sum(part_cost)*reduce_on_hand,
            saving_holding_costing = sum(cost_inventory)*reduce_on_hand)

final_ind_vel <- df_ind_vel %>% group_by(item_id,velocity, year) %>% 
  summarise(reduce_on_hand = round(mean(difference)*mean(lead_time)*mean(fcst_daily), 0),
            saving_part_cost = sum(part_cost)*reduce_on_hand,
            saving_holding_costing = sum(cost_inventory)*reduce_on_hand)

final_ind_mar <- df_ind_mar %>% group_by(item_id,marketing_category, year) %>% 
  summarise(reduce_on_hand = round(mean(difference)*mean(lead_time)*mean(fcst_daily), 0),
            saving_part_cost = sum(part_cost)*reduce_on_hand,
            saving_holding_costing = sum(cost_inventory)*reduce_on_hand)
 



```






```{r}
write.csv(final_vel, 'final_vel.csv',row.names=FALSE)
write.csv(final_mar, 'final_mar.csv',row.names=FALSE)
write.csv(final_ind_vel, 'final_ind_vel.csv', row.names=FALSE)
write.csv(final_ind_mar, 'final_ind_mar.csv', row.names=FALSE)
```
