---
title: "Paccar Parts Project"
author: ""
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
---


Commented header  
=========================================

```{r echo = TRUE}
# Course: MGMT 5200
# Title: Boardroom Analytics
# Purpose: Paccar Parts Project
# Date: 2019-07-24
# Author: 
```


Clear environment of variables and packages  
=========================================

```{r}
# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 

# Clear environmet of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), detach, character.only = TRUE, unload = TRUE)
```

Load packages that include different functions  
=========================================

```{r}
# adding library
library(tidyverse)
library(GGally)
library(gridExtra)
library("readxl")
library(janitor)
library(stringr)
library(aod)
library(ggplot2)
library(dplyr)
```

Load data and begin new EDA  
=========================================

```{r}
#loading data
annual_demand <- read_csv('../Data/annual_demand.csv')

demand <- read_csv('../Data/demand.csv')

fcst_error <- read_csv('../Data/fcst_error.csv')

future_fcst <- read_csv('../Data/future_fcst.csv')

item_location_count <- read_csv('../Data/item_location_count.csv')

lead_time <- read_csv('../Data/lead_time.csv')

ots <- read_csv('../Data/ots.csv')

part_information <- read_csv('../Data/part_information.csv')

protected_inventory <- read_csv('../Data/protected_inventory.csv')



```

```{r}
part_information$stock_class <- as.factor(part_information$stock_class)
part_information$stock_class_desc <- as.factor(part_information$stock_class_desc)
part_information$marketing_category <- as.factor(part_information$marketing_category)
part_information$desk <- as.factor(part_information$desk)
part_information$velocity <- as.factor(part_information$velocity)
part_information$vndr_id <- as.factor(part_information$vndr_id)
part_information$whse_stk_ind <- as.factor(part_information$whse_stk_ind)
part_information$natl_stk_ind <- as.factor(part_information$natl_stk_ind)
part_information$trp_ind <- as.factor(part_information$trp_ind)
part_information$mx_ind <- as.factor(part_information$mx_ind)
part_information$ngp_ind <- as.factor(part_information$ngp_ind)
part_information$lfna_ind <- as.factor(part_information$lfna_ind)
part_information$lfna_4c_ind <- as.factor(part_information$lfna_4c_ind)
part_information$unit_of_measure <- as.factor(part_information$unit_of_measure)

summary(part_information)
```


```{r}
length(unique(part_information$marketing_category))

```

```{r}
# Rfill, Rhit cost,
demand_fill <- demand %>%
                    mutate(year = format(order_month,'%Y')) %>%
                    select(year, dim, nline, rline, nhit, rhit, rhit_qty) %>%
                    group_by(year, dim) %>%
                    summarise( rfill = (1 - sum(rhit)/sum(rline)),
                               nfill = (1 - sum(nhit)/sum(nline)),
                               rhit_cost = sum(rhit)*15)

part_by_fill <- left_join(part_information, demand_fill, by = c("dim"="dim")) %>%
                  select(year, dim, marketing_category, velocity, on_hand, on_order, lead_time, vndr_id, fcst_3m, fcst_daily, safety_stock_days, safety_stock_qty, days_on_hand, part_cost, trp_ind, mx_ind, ngp_ind, lfna_ind, lfna_4c_ind, length, width, height, rfill, nfill, rhit_cost)

part_by_demand_fill <- left_join(part_by_fill, annual_demand, by = c("dim"="dim")) %>%
                  select(year, dim, marketing_category, velocity, on_hand, on_order, lead_time, vndr_id, fcst_3m, fcst_daily, safety_stock_days, safety_stock_qty, days_on_hand, part_cost, trp_ind, mx_ind, ngp_ind, lfna_ind, lfna_4c_ind, length, width, height, rfill, nfill, rhit_cost, "2014", "2015", "2016", "2017", "2018", "2019")

# filter vendors with PDC
ots = ots[ots$channel == 'PDC',]

ots$ots_month<- as.Date(ots$ots_month, format = "%m/%d/%Y")

# ots group by year and vendor
ots_by_year <- ots %>%
  mutate(year = format(ots_month,'%Y')) %>%                  
  select(year, vndr_id, early, on_time, pd_shipped, past_due, total_all) %>%
                    group_by(year, vndr_id) %>%
                    summarise( early      = sum(early),
                               on_time    = sum(on_time),
                               pd_shipped = sum(pd_shipped),
                               past_due   = sum(past_due),
                               total_all  = sum(total_all))

part_by_demand_fill <- left_join(part_by_demand_fill, ots_by_year, by = c("year"="year", "vndr_id" = "vndr_id")) %>%
                  select(year, dim, marketing_category, velocity, on_hand, on_order, lead_time, vndr_id, fcst_3m, fcst_daily, safety_stock_days, safety_stock_qty, days_on_hand, part_cost, trp_ind, mx_ind, ngp_ind, lfna_ind, lfna_4c_ind, length, width, height, rfill, nfill, rhit_cost, "2014", "2015", "2016", "2017", "2018", "2019", early, on_time, pd_shipped, past_due, total_all)

# part_by_marketing <- part_information %>%
#                 group_by(marketing_category) %>%
#                 mutate(in_stock = sum(on_hand),
#                        in_order = sum(on_order),
#                        avg_cost = mean(part_cost)) %>%
#                select(marketing_category, in_stock, in_order, avg_cost)
part_by_demand_fill$rfill[is.na(part_by_demand_fill$rfill)] <- 0
part_by_demand_fill$nfill[is.na(part_by_demand_fill$nfill)] <- 0
part_by_demand_fill$part_cost[is.na(part_by_demand_fill$part_cost)] <- 0
part_by_demand_fill$rhit_cost[is.na(part_by_demand_fill$rhit_cost)] <- 0
part_by_demand_fill$"2014"[is.na(part_by_demand_fill$"2014")] <- 0
part_by_demand_fill$"2015"[is.na(part_by_demand_fill$"2015")] <- 0
part_by_demand_fill$"2016"[is.na(part_by_demand_fill$"2016")] <- 0
part_by_demand_fill$"2017"[is.na(part_by_demand_fill$"2017")] <- 0
part_by_demand_fill$"2018"[is.na(part_by_demand_fill$"2018")] <- 0
part_by_demand_fill$"2019"[is.na(part_by_demand_fill$"2019")] <- 0
write.csv(part_by_demand_fill, file = "part_by_demand_fill.csv")

```



```{r}
summary(lead_time)
```


```{r}
summary(future_fcst)
```
















